// <auto-generated />
using System;
using Kinesis.Poc.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kinesis.Poc.Api.Data.Migrations
{
    [DbContext(typeof(PatientsDbContext))]
    [Migration("20260912213217_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kinesis.Poc.Api.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DocumentType", "DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Patients_Document")
                        .HasFilter("[DocumentType] IS NOT NULL AND [DocumentNumber] IS NOT NULL");

                    b.ToTable("Patients", null, t =>
                        {
                            t.HasCheckConstraint("CK_Patients_DocumentPair", "([DocumentType] IS NULL AND [DocumentNumber] IS NULL) OR ([DocumentType] IS NOT NULL AND [DocumentNumber] IS NOT NULL AND LEN(LTRIM(RTRIM([DocumentType]))) > 0 AND LEN(LTRIM(RTRIM([DocumentNumber]))) > 0)");

                            t.HasCheckConstraint("CK_Patients_FirstName", "LEN(LTRIM(RTRIM([FirstName]))) > 0");

                            t.HasCheckConstraint("CK_Patients_LastName", "LEN(LTRIM(RTRIM([LastName]))) > 0");

                            t.HasCheckConstraint("CK_Patients_Status", "[Status] IN (N'Active', N'Inactive')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
